# Generated by Django 4.2.2 on 2023-08-03 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_sent',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата предыдущей рассылки'),
            preserve_default=False,
        ),
    ]
